"""Added type for editing forecast

Revision ID: af1669152cd9
Revises: 409027ee7ed2
Create Date: 2024-10-22 22:33:51.500643

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'af1669152cd9'
down_revision = '409027ee7ed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
